### ISSUE TITLE
bug: suave-viem is not updated for Toliman

### ISSUE THREAD

**Issue by pistomat** [flashbots/suave-viem#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.0.0-main.20240703T192338

### Current Behavior

This package does not have specs for Toliman, for example the chain id changed. RPC requests throw this errror
```
shortMessage: 'RPC Request failed.',
    version: 'viem@0.0.0-main.20240703T192338',
    cause: {
      code: -32000,
      message: 'invalid chain id for signer: have 33626250 want 16813125'
    },
```
because the `SuaveProvider` type is hardcoded to be typeof `suaveRigil

### Expected Behavior

There should be a config which testnet you are using. Also should be configurable to work with local `suave-geth` testnet running both Rigil and Toliman specs.

**Comment by zeroXbrock** [comment]
thanks for the issue @pistomat -- resolved in a32aa32e6d2ec22fa5c4a807a61a1bdbe3cf6240. Note that Rigil is still supported because the local devnet still uses the Rigil chain ID. The client will detect the appropriate network for wallets based on `customRpc` (calling `getSuaveWallet`), so if you're connecting to the toliman public testnet, using this commit it will automatically set the correct chainId. If you haven't already, update/add `@flashbots/suave-viem@main` with yarn/bun/npm to get the latest developer release, which includes this commit.
Lmk if you have any issues with it!
